#include "includes/coordinates_graphic.h"

/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/



/**
* Sets position and graphic look of speed mode menu
* @param playDirectionBox Graphic box to group move direction buttons.
* @param Label letterCoordinates for indicating number of columns
* @param Label numCoor1 for indicating number of row
* @param Label numCoor2 for indicating number of row
* @param Label numCoor3 for indicating number of row
* @param Label numCoor4 for indicating number of row
* @param Label numCoor5 for indicating number of row
* @param Label numCoor6 for indicating number of row
* @param Label numCoor7 for indicating number of row
* @param Label numCoor8 for indicating number of row
*/

void coordinatesGraphic :: drawCoordinates(QLabel * letterCoordinates, QLabel * numCoor1, QLabel * numCoor2, QLabel * numCoor3, QLabel *numCoor4, QLabel * numCoor5, QLabel * numCoor6, QLabel * numCoor7, QLabel * numCoor8)
{    //Creating font for graphic interface
  //Generated by QtCreator
  QFont font6;
  font6.setPointSize(19);
  font6.setBold(true);
  font6.setItalic(false);
  font6.setWeight(75);
  font6.setFamily(QStringLiteral("DejaVu Serif"));

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  letterCoordinates->setFont(font6);
  letterCoordinates->setText("      A         B         C         D         E         F         G         H");
  letterCoordinates->setGeometry(QRect(60, 820, 921, 31));

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor1->setFont(font6);
  numCoor1->setText("1");;
  numCoor1->setGeometry(QRect(45, 740, 31, 31));

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor2->setText("2");
  numCoor2->setGeometry(QRect(45, 640, 21, 31));
  numCoor2->setFont(font6);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor3->setText("3");
  numCoor3->setGeometry(QRect(45, 540, 21, 31));
  numCoor3->setFont(font6);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor4->setText("4");
  numCoor4->setGeometry(QRect(45, 440, 21, 31));
  numCoor4->setFont(font6);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor5->setText("5");
  numCoor5->setGeometry(QRect(45, 340, 21, 31));
  numCoor5->setFont(font6);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor6->setGeometry(QRect(45, 240, 21, 31));
  numCoor6->setFont(font6);
  numCoor6->setText("6");

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor7->setText("7");
  numCoor7->setGeometry(QRect(45, 150, 21, 31));
  numCoor7->setFont(font6);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  numCoor8->setText("8");
  numCoor8->setGeometry(QRect(45, 50, 21, 31));
  numCoor8->setFont(font6);


}
