#include "includes/dialog_graphic.h"



/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/


//Generated by QtCreator

/**
* Sets position and graphic look of dialog menu
* @param userInSubmit Button for choosing a speed delay of moves.
* @param movetList Button for choosing a speed delay of moves.
* @param inputTextLabel Label for title.
* @param moveListLabel Label for title.
*/
void dialogGraphic :: setUpTabListDialog(QPlainTextEdit * userInSubmit, QListWidget * movetList, QLabel * inputTextLabel, QLabel * moveListLabel)
{
  //Creating font for graphic interface
  //Generated by QtCreator
  QFont font3;
  font3.setFamily(QStringLiteral("Carlito"));
  font3.setPointSize(15);
  font3.setBold(true);
  font3.setWeight(75);
  //Setting up TextEdit and adjusting graphic elements
  //Generated by QtCreator
  userInSubmit->setEnabled(true);
  userInSubmit->setGeometry(QRect(1280, 70, 201, 161));
  userInSubmit->setAutoFillBackground(false);
  userInSubmit->setStyleSheet(QLatin1String("*:enabled{background-color: rgb(255, 255, 255);}\n""*:disabled{background-color: rgb(211, 215, 207);}\n""\n""\n"""));

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  inputTextLabel->setText("User input");
  inputTextLabel->setGeometry(QRect(1300, 20, 151, 41));
  inputTextLabel->setFont(font3);
  inputTextLabel->setAlignment(Qt::AlignCenter);

  //Setting up list widget and adjusting graphic elements
  //Generated by QtCreator
  movetList->setGeometry(QRect(1060, 70, 201, 161));
  movetList->setStyleSheet(QLatin1String("*:enabled{background-color: rgb(255, 255, 255);}\n""*:disabled{color: rgb(0, 0, 0);background-color: rgb(255, 255, 255)}\n""\n""\n"""));

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  moveListLabel->setText("Move list");
  moveListLabel->setGeometry(QRect(1080, 20, 151, 41));
  moveListLabel->setFont(font3);
  moveListLabel->setAlignment(Qt::AlignCenter);


}
/**
* Sets position and graphic look of dialog buttons
* @param userMoveLabel Label for title.
* @param submitButton Button for submit file.
* @param redoButton Button for redoing  moves.
* @param undoButton Button for undoing moves.
* @param saveButton Button for saving files.
*/

void dialogGraphic :: setUpUserInputButtons(QLabel * userMoveLabel, QPushButton * submitButton, QPushButton * redoButton, QPushButton * undoButton, QPushButton * saveButton)
{  //Creating font for graphic interface
  //Generated by QtCreator
  QFont font3;
  font3.setFamily(QStringLiteral("Carlito"));
  font3.setPointSize(15);
  font3.setBold(true);
  font3.setWeight(75);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  userMoveLabel->setText("User move control");
  userMoveLabel->setGeometry(QRect(1150, 250, 271, 41));
  userMoveLabel->setFont(font3);
  userMoveLabel->setAlignment(Qt::AlignCenter);

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  undoButton->setText("Undo");
  undoButton->setGeometry(QRect(1030, 300, 111, 41));
  undoButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  redoButton->setText("Redo");
  redoButton->setGeometry(QRect(1150, 300, 111, 41));
  redoButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  saveButton->setText("Save");
  saveButton->setEnabled(true);
  saveButton->setGeometry(QRect(1390, 300, 111, 41));
  saveButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  submitButton->setText("Submit");
  submitButton->setGeometry(QRect(1270, 300, 111, 41));
  submitButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""background-color:rgb(233, 185, 110)\n""}"));
};
