#include "includes/modebox_graphic.h"


/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/


/**
* Sets position and graphic look of mode menu
* @param gameModGroup Graphic box for game mode buttons..
* @param autoButton Button for activation of automatic controls.
* @param manualButton Button for activation of manual controls.
*/
void modeMenuGraphic :: setUpGameModeMenu(QGroupBox * gameModGroup, QPushButton * autoButton, QPushButton * manualButton)
{
    //Creating font for graphic interface
        //Generated by QtCreator
  QFont font2;
  font2.setFamily(QStringLiteral("Carlito"));
  font2.setPointSize(13);
  font2.setBold(true);
  font2.setWeight(75);

  //Setting up button box and adjusting graphic elements
      //Generated by QtCreator
  gameModGroup->setGeometry(QRect(1060, 540, 411, 111));
  gameModGroup->setFont(font2);
  gameModGroup->setTitle("Game mode");
  gameModGroup->setAlignment(Qt::AlignCenter);

  //Setting up button and adjusting graphic elements
      //Generated by QtCreator
  autoButton->setText("Automatic");
  autoButton->setGeometry(QRect(20, 60, 171, 51));
  autoButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));

  //Setting up button and adjusting graphic elements
      //Generated by QtCreator
  manualButton->setText("Manual");
  manualButton->setGeometry(QRect(220, 60, 171, 51));
  manualButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));


}
