#include "includes/movebox_graphic.h"


/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/


/**
* Sets position and graphic look of move menu
* @param whiteMoveLabel Label indicating turn of player.
* @param blackMoveLabel Label indicating turn of player.
* @param gameMoveGroup Graphic box for move direction buttons.
* @param prevMoveButton Button for choosing move on previous move.
* @param nextMoveButton Button for choosing a speed delay of moves.
*/

void moveMenuGraphic :: setUpMoveMenu(QLabel * whiteMoveLabel, QLabel * blackMoveLabel, QGroupBox * gameMoveGroup, QPushButton * prevMoveButton, QPushButton * nextMoveButton)
{
      //Creating font for graphic interface
      //Generated by QtCreator
  QFont font3;
  font3.setFamily(QStringLiteral("Carlito"));
  font3.setPointSize(15);
  font3.setBold(true);
  font3.setWeight(75);
    //Creating font for graphic interface
    //Generated by QtCreator
  QFont font4;
  font4.setFamily(QStringLiteral("Carlito"));
  font4.setPointSize(13);
  font4.setBold(true);
  font4.setItalic(false);
  font4.setWeight(75);
    //Creating font for graphic interface
    //Generated by QtCreator
  QFont font5;
  font5.setFamily(QStringLiteral("Abyssinica SIL"));
  font5.setPointSize(15);
  font5.setBold(true);
  font5.setItalic(false);
  font5.setWeight(75);

  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  whiteMoveLabel->setText("White on the move");
  whiteMoveLabel->setEnabled(true);
  whiteMoveLabel->setGeometry(QRect(1010, 370, 241, 31));
  whiteMoveLabel->setFont(font5);
  whiteMoveLabel->setAlignment(Qt::AlignCenter);
  //Setting up label and adjusting graphic elements
  //Generated by QtCreator
  blackMoveLabel->setText("Black on the move");
  blackMoveLabel->setEnabled(false);
  blackMoveLabel->setGeometry(QRect(1270, 370, 231, 31));
  blackMoveLabel->setFont(font5);
  blackMoveLabel->setAlignment(Qt::AlignCenter);

  //Setting up button box and adjusting graphic elements
  //Generated by QtCreator
  gameMoveGroup->setTitle("Move control");
  gameMoveGroup->setGeometry(QRect(1060, 420, 411, 111));
  gameMoveGroup->setFont(font4);
  gameMoveGroup->setAutoFillBackground(false);
  gameMoveGroup->setAlignment(Qt::AlignCenter);
  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  prevMoveButton->setText("Previous move");
  prevMoveButton->setGeometry(QRect(20, 60, 171, 51));
  prevMoveButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));
  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  nextMoveButton->setText("Next move");;
  nextMoveButton->setGeometry(QRect(220, 60, 171, 51));
  nextMoveButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));
}
