#include "includes/reset_graphic.h"


/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/


/**
* Sets position and graphic look of reset button
* @param restartButton points to button, which is supposed to be decorated
*/

void resetGraphic :: setUpResetButton(QPushButton * restartButton)
{
  //Creating font
  QFont font1;
  font1.setPointSize(16);
  //Setting graphic elements
  //Generated by QtCreator
  restartButton->setGeometry(QRect(1210, 760, 121, 41));
  restartButton->setFont(font1);
  restartButton->setStyleSheet(QLatin1String("QPushButton\n""{\n""   background-color:rgb(233, 185, 110)\n""}"));
  restartButton->setText("Restart");
}
