#include "includes/speedbox_graphic.h"


/**
*@author Jaromir Hradil, xhradi15@fit.vutbr.cz
*/


/**
* Sets position and graphic look of speed mode menu
* @param playDirectionBox Graphic box to group move direction buttons.
* @param speedButton1 Button for choosing a speed delay of moves.
* @param speedButton2 Button for choosing a speed delay of moves.
* @param speedButton3 Button for choosing a speed delay of moves.
* @param speedButton4 Button for choosing a speed delay of moves.
* @param speedButton5 Button for choosing a speed delay of moves.
*/
void speedMenuGraphic :: setUpSpeedMenu(QGroupBox * speedBox, QRadioButton * speedButton1, QRadioButton * speedButton2, QRadioButton * speedButton3, QRadioButton * speedButton4, QRadioButton * speedButton5)
{
    //Creating font for graphic interface
    //Generated by QtCreator
  QFont font2;
  font2.setFamily(QStringLiteral("Carlito"));
  font2.setPointSize(13);
  font2.setBold(true);
  font2.setWeight(75);

  //Setting up button box and adjusting graphic elements
  //Generated by QtCreator
  speedBox->setEnabled(true);
  speedBox->setGeometry(QRect(990, 670, 341, 71));
  speedBox->setTitle("Auto speed");
  speedBox->setFont(font2);
  speedBox->setAlignment(Qt::AlignCenter);

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  speedButton1->setText("||");
  speedButton1->setGeometry(QRect(40, 40, 61, 25));
  speedButton1->setStyleSheet(QLatin1String("background-color:rgb(233, 185, 110)\n"""));
  speedButton1->setChecked(true);

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  speedButton2->setText("0.5s");
  speedButton2->setGeometry(QRect(90, 40, 61, 25));
  speedButton2->setStyleSheet(QStringLiteral("background-color:rgb(233, 185, 110)"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  speedButton3->setText("1s");
  speedButton3->setGeometry(QRect(150, 40, 61, 25));
  speedButton3->setStyleSheet(QStringLiteral("background-color:rgb(233, 185, 110)"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  speedButton4->setText("2s");
  speedButton4->setGeometry(QRect(200, 40, 61, 25));
  speedButton4->setStyleSheet(QStringLiteral("background-color:rgb(233, 185, 110)"));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  speedButton5->setText("3s");
  speedButton5->setGeometry(QRect(260, 40, 61, 25));
  speedButton5->setStyleSheet(QStringLiteral("background-color:rgb(233, 185, 110)"));

}

/**
* Sets position and graphic look of direction mode menu
* @param playDirectionBox Graphic box to group move direction buttons.
* @param directionButtonB Button for moving back during autoplay.
* @param directionButtonF Button for moving forward during autoplay.
*/

void speedMenuGraphic :: setUpPlayMenu(QGroupBox * playDirectionBox, QRadioButton * directionButtonB, QRadioButton * directionButtonF)
{
  //Creating fong for grapgic interface
  //Generated by QtCreator
  QFont font2;
  font2.setFamily(QStringLiteral("Carlito"));
  font2.setPointSize(13);
  font2.setBold(true);
  font2.setWeight(75);

  //Setting up button box and adjusting graphic elements
  //Generated by QtCreator
  playDirectionBox->setTitle("Play direction");;
  playDirectionBox->setEnabled(true);
  playDirectionBox->setGeometry(QRect(1330, 670, 171, 71));
  playDirectionBox->setFont(font2);
  playDirectionBox->setAlignment(Qt::AlignCenter);

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  directionButtonB->setText("<<");
  directionButtonB->setGeometry(QRect(20, 40, 61, 25));
  directionButtonB->setStyleSheet(QLatin1String("background-color:rgb(233, 185, 110)\n"""));

  //Setting up button and adjusting graphic elements
  //Generated by QtCreator
  directionButtonF->setText(">>");
  directionButtonF->setGeometry(QRect(90, 40, 61, 25));
  directionButtonF->setStyleSheet(QStringLiteral("background-color:rgb(233, 185, 110)"));
  directionButtonF->setChecked(true);



}
